services:
  vod-server:
    image: nginx-rtmp:1.0.0
    ports:
      - 8000:80
      - 1935:1935
    volumes:
      - ./nginx/conf:/usr/local/nginx/conf
      - ./nginx/logs:/usr/local/nginx/logs
      - ./nginx/html/stream:/usr/local/nginx/html/stream
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 3
        order: start-first
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/index.html"]
      #test: ["CMD-SHELL", "exit 0"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s
volumes:
  etc-nginx:
  logs-nginx:
  stream-nginx:
